#!/usr/bin/env sh
# YABAI CONFIG

## Layout
# bsp or float (default: bsp)
yabai -m config layout bsp

# Override default layout for space 2 only
# yabai -m config --space 2 layout float

# By default, new windows become the right or bottom split when tiled, which can be changed to left or top

## New window spawns to the left or top
# yabai -m config window_placement first_child
## New window spawns to the right or bottom
# yabai -m config window_placement second_child

## Padding and gaps

# Setting paddings
yabai -m config top_padding 2
yabai -m config bottom_padding 2
yabai -m config left_padding 2
yabai -m config right_padding 2
yabai -m config window_gap 4

## Override gaps for space 2 only
# yabai -m config --space 2 window_gap 0

## Split ratios

# Auto balance
yabai -m config auto_balance off

# split ratio
yabai -m config split_ratio 0.5

## Mouse support
yabai -m config mouse_modifier ctrl

# modifier + left-click
yabai -m config mouse_action1 move

# modifier + right-click
yabai -m config mouse_action2 resize

# whether focus follows mouse off/autoraise/autofocus
yabai -m config focus_follows_mouse off

# whether mouse follows focus off/on
yabai -m config mouse_follows_focus off

## Window modifications

# floating windows are always on top
yabai -m config window_topmost on

# window shadows: on/off/float
yabai -m config window_shadow float

# window opacity on/off
yabai -m config window_opacity off 
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.9

## Window border
yabai -m config window_border on
yabai -m config window_border_width 3
yabai -m config active_window_border_color 0xff40ff00
yabai -m config normal_window_border_color 0x00FFFFFF
yabai -m config insert_feedback_color 0xffd75f5f

## float system preferences
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on manage=off
yabai -m rule --add app="^Nutstore" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^iTerm2$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^root" manage=off
yabai -m rule --add app="^zoom" manage=off

# yabai -m signal --add event=window_destroyed action="bash /Users/ycwu/Workingspace/dotfiles/yabai-skhd/window-focus-on-destroy.sh"

echo "YABAI CONFIGURATION LOADED..."
